// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── WEB ──────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfTGmdX75vKs380m0zGWi8rtVRLDHuOA',
    appId: '1:523997606244:web:d1dba582a4f081f8350a71',
    messagingSenderId: '523997606244',
    projectId: 'smartstock2',
    authDomain: 'smartstock2.firebaseapp.com',
    storageBucket: 'smartstock2.firebasestorage.app',
    measurementId: 'G-JT0MLG5EFF',
  );

  // ── ANDROID ───────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUfTGmdX75vKs380m0zGWi8rtVRLDHuOA',
    appId: '1:523997606244:android:73032897d0b4b574350a71',
    messagingSenderId: '523997606244',
    projectId: 'smartstock2',
    storageBucket: 'smartstock2.firebasestorage.app',
  );

  // ── iOS ───────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUfTGmdX75vKs380m0zGWi8rtVRLDHuOA',
    appId: '1:523997606244:ios:73032897d0b4b574350a71',
    messagingSenderId: '523997606244',
    projectId: 'smartstock2',
    storageBucket: 'smartstock2.firebasestorage.app',
    iosBundleId: 'com.example.smartStock2',
  );

  // ── macOS ─────────────────────────────────────────────────────────
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUfTGmdX75vKs380m0zGWi8rtVRLDHuOA',
    appId: '1:523997606244:ios:73032897d0b4b574350a71',
    messagingSenderId: '523997606244',
    projectId: 'smartstock2',
    storageBucket: 'smartstock2.firebasestorage.app',
    iosBundleId: 'com.example.smartStock2',
  );

  // ── WINDOWS ───────────────────────────────────────────────────────
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUfTGmdX75vKs380m0zGWi8rtVRLDHuOA',
    appId: '1:523997606244:web:d1dba582a4f081f8350a71',
    messagingSenderId: '523997606244',
    projectId: 'smartstock2',
    storageBucket: 'smartstock2.firebasestorage.app',
  );
}

// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAn1kUxvH-gfodlRI1wxjqOGG2aUgeMkuk',
//     appId: '1:523997606244:android:73032897d0b4b574350a71',
//     messagingSenderId: '523997606244',
//     projectId: 'smartstock2',
//     storageBucket: 'smartstock2.firebasestorage.app',
//   );
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAUfTGmdX75vKs380m0zGWi8rtVRLDHuOA',
//     appId: '1:523997606244:web:d1dba582a4f081f8350a71',
//     messagingSenderId: '523997606244',
//     projectId: 'smartstock2',
//     authDomain: 'smartstock2.firebaseapp.com',
//     storageBucket: 'smartstock2.firebasestorage.app',
//     measurementId: 'G-3DQ4MBCLT8',
//   );
//
// }