// ════════════════════════════════════════════════════════════════════
//  lib/config/firebase_config.dart
//
//  ✅ This file is just a reference/constants file.
//  ✅ The REAL Firebase init happens in lib/firebase_options.dart
//     which is auto-generated by: flutterfire configure
//
//  ⚠️  DO NOT paste JavaScript code here.
//  ⚠️  DO NOT import { initializeApp } — that is JavaScript, not Dart.
// ════════════════════════════════════════════════════════════════════

class FirebaseConfig {
  FirebaseConfig._();

  // Your Firebase project details (for reference only)
  // The actual initialization uses lib/firebase_options.dart
  static const String projectId        = 'smartstock2';
  static const String authDomain       = 'smartstock2.firebaseapp.com';
  static const String storageBucket    = 'smartstock2.firebasestorage.app';
  static const String messagingSenderId = '523997606244';

  // Admin credentials (used for role detection in Firestore)
  static const String adminEmail       = 'admin@smartstock.com';

  // Firestore collection names
  static const String colUsers         = 'users';
  static const String colAdmins        = 'admins';
  static const String colProducts      = 'products';
  static const String colOrders        = 'orders';
  static const String colCart          = 'cart';
  static const String colFavorites     = 'favorites';
  static const String colSuppliers     = 'suppliers';
  static const String colPurchases     = 'purchases';
  static const String colTransfers     = 'stock_transfers';
  static const String colNotifications = 'notifications';
  static const String colReports       = 'reports';
}